name: flutter_playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  hex: ^0.2.0
  http: ^1.2.0
  provider: ^6.1.2
  solana: ^0.31.0
  web3auth_flutter: ^6.1.1
  web3dart: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/