name: sfa_flutter_aggregate_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  auth0_flutter: ^1.1.0
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  http: ^1.2.2
  provider: ^6.1.2
  single_factor_auth_flutter: ^6.0.1
  web3dart: ^2.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
